name: deepectransformer
channels:
  - pytorch
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - pip=19.3.1=py36_0
  - python_abi=3.6
  - biopython=1.78
  - diamond==2.0.11
  - matplotlib
  - pip:
    - tqdm==4.53.0
    - transformers==3.5.1
    - torch==1.7.0
